default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: cat-chat-development
  username:
  password:

test:
  <<: *default
  database: cat-chat-test
  username:
  password:

production:
  <<: *default
  database: cat-chat-production
  username: cat-chat-admin
  password: Rails.application.credentials.gcp[:db_password]
